export const COVER_LETTER_TITLE_REQUEST = "COVER_LETTER_TITLE_REQUEST";
export const COVER_LETTER_TITLE_SUCCESS = "COVER_LETTER_TITLE_SUCCESS";
export const COVER_LETTER_TITLE_FAIL = "COVER_LETTER_TITLE_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
