export const COVER_LETTER_TITLE_REQUEST = "COVER_LETTER_TITLE_REQUEST";
export const COVER_LETTER_TITLE_SUCCESS = "COVER_LETTER_TITLE_SUCCESS";
export const COVER_LETTER_TITLE_FAIL = "COVER_LETTER_TITLE_FAIL";

export const GET_COVER_LETTER_TITLE_REQUEST = "GET_COVER_LETTER_TITLE_REQUEST";
export const GET_COVER_LETTER_TITLE_SUCCESS = "GET_COVER_LETTER_TITLE_SUCCESS";
export const GET_COVER_LETTER_TITLE_FAIL = "GET_COVER_LETTER_TITLE_FAIL";

export const SELECTED_COVER_LETTER_TEMPLATE_REQUEST =
  "SELECTED_COVER_LETTER_TEMPLATE_REQUEST";
export const SELECTED_COVER_LETTER_TEMPLATE_SUCCESS =
  "SELECTED_COVER_LETTER_TEMPLATE_SUCCESS";
export const SELECTED_COVER_LETTER_TEMPLATE_FAIL =
  "SELECTED_COVER_LETTER_TEMPLATE_FAIL";

export const GET_SELECTED_COVER_LETTER_TEMPLATE_REQUEST =
  "GET_SELECTED_COVER_LETTER_TEMPLATE_REQUEST";
export const GET_SELECTED_COVER_LETTER_TEMPLATE_SUCCESS =
  "GET_SELECTED_COVER_LETTER_TEMPLATE_SUCCESS";
export const GET_SELECTED_COVER_LETTER_TEMPLATE_FAIL =
  "GET_SELECTED_COVER_LETTER_TEMPLATE_FAIL";

export const COVER_LETTER_DATA_REQUEST = "COVER_LETTER_DATA_REQUEST";
export const COVER_LETTER_DATA_SUCCESS = "COVER_LETTER_DATA_SUCCESS";
export const COVER_LETTER_DATA_FAIL = "COVER_LETTER_DATA_FAIL";

export const GET_COVER_LETTER_DATA_REQUEST = "GET_COVER_LETTER_DATA_REQUEST";
export const GET_COVER_LETTER_DATA_SUCCESS = "GET_COVER_LETTER_DATA_SUCCESS";
export const GET_COVER_LETTER_DATA_FAIL = "GET_COVER_LETTER_DATA_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
