export const RESUME_DATA = "RESUME_DATA";
export const COVER_LETTER_DATA = "COVER_LETTER_DATA";

export const SELECTED_RESUME_TEMPLATE_REQUEST =
  "SELECTED_RESUME_TEMPLATE_REQUEST";
export const SELECTED_RESUME_TEMPLATE_SUCCESS =
  "SELECTED_RESUME_TEMPLATE_SUCCESS";
export const SELECTED_RESUME_TEMPLATE_FAIL = "SELECTED_RESUME_TEMPLATE_FAIL";
export const SELECTED_RESUME_TEMPLATE_RESET = "SELECTED_RESUME_TEMPLATE_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
