export const RESUME_DATA = "RESUME_DATA";
export const COVER_LETTER_DATA = "COVER_LETTER_DATA";

export const RESUME_DATA_REQUEST = "RESUME_DATA_REQUEST";
export const RESUME_DATA_SUCCESS = "RESUME_DATA_SUCCESS";
export const RESUME_DATA_FAIL = "RESUME_DATA_FAIL";

export const GET_RESUME_DATA_REQUEST = "GET_RESUME_DATA_REQUEST";
export const GET_RESUME_DATA_SUCCESS = "GET_RESUME_DATA_SUCCESS";
export const GET_RESUME_DATA_FAIL = "GET_RESUME_DATA_FAIL";

export const SELECTED_RESUME_TEMPLATE_REQUEST =
  "SELECTED_RESUME_TEMPLATE_REQUEST";
export const SELECTED_RESUME_TEMPLATE_SUCCESS =
  "SELECTED_RESUME_TEMPLATE_SUCCESS";
export const SELECTED_RESUME_TEMPLATE_FAIL = "SELECTED_RESUME_TEMPLATE_FAIL";
export const SELECTED_RESUME_TEMPLATE_RESET = "SELECTED_RESUME_TEMPLATE_RESET";

export const GET_SELECTED_RESUME_TEMPLATE_REQUEST =
  "GET_SELECTED_RESUME_TEMPLATE_REQUEST";
export const GET_SELECTED_RESUME_TEMPLATE_SUCCESS =
  "GET_SELECTED_RESUME_TEMPLATE_SUCCESS";
export const GET_SELECTED_RESUME_TEMPLATE_FAIL =
  "GET_SELECTED_RESUME_TEMPLATE_FAIL";

export const RESUME_TITLE_REQUEST = "RESUME_TITLE_REQUEST";
export const RESUME_TITLE_SUCCESS = "RESUME_TITLE_SUCCESS";
export const RESUME_TITLE_FAIL = "RESUME_TITLE_FAIL";

export const GET_RESUME_TITLE_REQUEST = "GET_RESUME_TITLE_REQUEST";
export const GET_RESUME_TITLE_SUCCESS = "GET_RESUME_TITLE_SUCCESS";
export const GET_RESUME_TITLE_FAIL = "GET_RESUME_TITLE_FAIL";

export const REMOVE_PROFILE_IMAGE_REQUEST = "REMOVE_PROFILE_IMAGE_REQUEST";
export const REMOVE_PROFILE_IMAGE_SUCCESS = "REMOVE_PROFILE_IMAGE_SUCCESS";
export const REMOVE_PROFILE_IMAGE_FAIL = "REMOVE_PROFILE_IMAGE_FAIL";
export const REMOVE_PROFILE_IMAGE_RESET = "REMOVE_PROFILE_IMAGE_RESET";

export const GET_ALL_RESUMES_DATA = "GET_ALL_RESUMES_DATA";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
